# Creates and subscribes to an SNS topic for lambda event triggers
---
- name: Retrieve update-s3-storage-prices Lambda Details
  lambda_facts:
    region: "{{ region }}"
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    query: all
    function_name: '{{ update_lambda_function }}'
  register: lambda_facts.function

- name: Print output
  debug:
    msg: "Lambda Arn: {{ lambda_facts.function['update-s3-storage-prices'].function_arn }}"

- name: Create Lambda SNS Topic
  sns_topic:
    region: "{{ region }}"
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    name: "test"
    state: present
    display_name: "{{ sns_topic_name }}"
    delivery_policy:
      http:
        defaultHealthyRetryPolicy:
            minDelayTarget: 2
            maxDelayTarget: 4
            numRetries: 5
            numMaxDelayRetries: 5
            backoffFunction: "arithmetic"
        disableSubscriptionOverrides: True
        defaultThrottlePolicy:
            maxReceivesPerSecond: 10
    subscriptions:
      - endpoint: "{{ lambda_facts.function['update-s3-storage-prices'].function_arn }}"
        protocol: "lambda"