# Creates and subscribes to an SNS topic for lambda event triggers
---
- name: Retrieve update-s3-storage-prices Lambda Details
  lambda_facts:
    region: "{{ region }}"
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    query: all
    function_name: '{{ receive_lambda_function }}'
  register: lambda_facts.function

- name: Print lambda_facts.function output
  debug:
    msg: "Lambda Arn: {{ lambda_facts.function['ReceiveVotes'].function_arn }}"

- name: Create Lambda SNS Topic
  sns_topic:
    region: "{{ region }}"
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    name: "{{ sns_topic_name }}"
    state: present
    display_name: "{{ sns_topic_name }}"
    subscriptions:
      - endpoint: "{{ lambda_facts.function['ReceiveVotes'].function_arn }}"
        protocol: "lambda"
  register: sns_topic

- name: Print Topic ARN output
  debug:
    msg: "SNS Topic ARN Details: {{ sns_topic['sns_arn'] }}"


- name: Confirm SNS Permission for Lambda
  command: python /Users/annadowling/Desktop/CloudArch/ansible-architecture/playbooks/addPermissionToLambda.py {{ access_key_id }} {{ secret_access_key }} {{ sns_topic['sns_arn'] }}