# Creates and subscribes to an SNS topic for lambda event triggers
---
- name: Create Lambda SNS topic
  sns_topic:
    region: "{{ region }}"
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    name: "{{ price_change_sns_topic_arn }}"
    state: present
    display_name: "{{ sns_topic_name }}"
    delivery_policy:
      http:
        defaultHealthyRetryPolicy:
            minDelayTarget: 2
            maxDelayTarget: 4
            numRetries: 3
            numMaxDelayRetries: 5
            backoffFunction: "arithmetic"
        disableSubscriptionOverrides: True
        defaultThrottlePolicy:
            maxReceivesPerSecond: 10
    subscriptions:
      - endpoint: "update-s3-storage-prices lambda function arn TO BE QUERIED FOR AND FILLED IN HERE"
        protocol: "lambda"
