# Deletes an SNS topic for lambda event triggers
---
- name: Delete Lambda SNS Topic
  sns_topic:
    region: "{{ region }}"
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    name: "{{ sns_topic_name }}"
    state: absent
