# Create dynamo tables with hash primary key
---
- name: Create DynamoDB Tables
  dynamodb_table:
    region: "{{ region }}"
    name: "{{ item.table_name }}"
    hash_key_name: "{{ hash_key_name }}"
    hash_key_type: STRING
    read_capacity: 2
    write_capacity: 2
    tags:
      tag_name: "{{ item.tag }}"
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
  with_items:
    - table_name: "{{ vote_table }}"
      tag: "{{ vote_tag }}"
    - table_name: "{{ vote_agg_table }}"
      tag: "{{ vote_agg_tag }}"