# Delete s3 bucket and files
---
- name: Create S3 Bucket
  aws_s3:
    region: "{{ region }}"
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    bucket: "{{ s3_bucket_name }}"
    mode: delete
