# Create Lambda functions
---
- name: Create Lamda Function Loop
  lambda:
    name: '{{ item.name }}'
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    region: "{{ region }}"
    state: present
    zip_file: '{{ item.zip_file }}'
    runtime: 'nodejs6.10'
    handler: '{{ item.handler }}'
    role: '{{ lambda_role }}'
  with_items:
    - name: '{{ receive_lambda_function }}'
      zip_file: '{{ zip_file_receive_function }}'
      handler: '{{ received_handler }}'
    - name: '{{ agg_lambda_function }}'
      zip_file: '{{ zip_file_agg_function }}'
      handler: '{{ agg_handler }}'

- name: Create Dev alias for Lambda functions
  lambda_alias:
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    region: "{{ region }}"
    state: present
    function_name: "{{ item.name }}"
    name: Dev
    description: Development is $LATEST version
    version: 0
  with_items:
    - name: '{{ receive_lambda_function }}'
    - name: '{{ agg_lambda_function }}'
