# Create Lambda functions
---
- name: Create Lamda Function Loop
  lambda:
    name: '{{ item.name }}'
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    region: "{{ region }}"
    state: present
    zip_file: '{{ item.zip_file }}'
    runtime: 'nodejs6.10'
  with_items:
    - name: '{{ update_lambda_function }}'
      zip_file: '{{ zip_file_update }}'
    - name: '{{ update_lambda_function }}'
      zip_file: '{{ zip_file_get }}'
