# Create Lambda functions
---
- name: Create Lamda Function Loop
  lambda:
    name: '{{ item.name }}'
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    region: "{{ region }}"
    state: present
    zip_file: '{{ item.zip_file }}'
    runtime: 'python2.7'
    handler: 'hello_python.my_handler'
    environment_variables: '{{ item.env_vars }}'
    tags:
      key1: 'value1'
  with_items:
    - name: HelloWorld
      zip_file: hello-code.zip
      env_vars:
        key1: "first"
        key2: "second"
    - name: ByeBye
      zip_file: bye-code.zip
      env_vars:
        key1: "1"
        key2: "2"
