# Creates3 bucket and upload html file
---
- name: Create S3 Bucket
  s3_bucket:
    region: "{{ region }}"
    name: "{{ s3_bucket_name }}"
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
  register: bucket

- name: Sync Sample App to my bucket
  s3_sync:
    bucket: "{{ s3_bucket_name }}"
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    file_root: "{{ webapp_file_dir }}"

#- name: PUT html file in bucket
#  aws_s3:
#    region: "{{ region }}"
#    aws_access_key: "{{ access_key_id }}"
#    aws_secret_key: "{{ secret_access_key }}"
#    bucket: "{{ s3_bucket_name }}"
#    object: "{{ object_key }}"
#    src: "{{ html_file_dir }}"
#    mode: put
#    permission: public-read
