# Creates3 bucket and upload html file
---
- name: Create S3 Bucket
  aws_s3:
    region: "{{ region }}"
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    bucket: "{{ s3_bucket_name }}"
    mode: create
    permission: public-read

- name: Sync AppFiles to my bucket
  s3_sync:
    bucket: "{{ s3_bucket_name }}"
    region: "{{ region }}"
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    file_root: "{{ webapp_file_dir }}"
    permission: public-read

- name: Set Bucket as a Static Web Host
  s3_website:
    region: "{{ region }}"
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    name: "{{ s3_bucket_name }}"
    suffix: index.html
    error_key: error.html
    state: present