# Create dynamo table with hash and range primary key
---
- name: Retrieve DynamoDB Table ARN
  command: python /Users/annadowling/Desktop/CloudArch/ansible-architecture/playbooks/retrieveDynamoDBTableARN.py {{ access_key_id }} {{ secret_access_key }}
  register: dynamodb_table_arn

- name: Print output
  debug:
    msg: "DYNAMODB Arn: {{ dynamodb_table_arn }}"

- name: Create DynamoDB Event Trigger for Aggregation Lambda
  lambda_event:
    region: "{{ region }}"
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    state: present
    event_source: stream
    function_name: "{{ agg_lambda_function }}"
    alias: "{{ agg_lambda_function }}"
    source_params:
      source_arn: "{{ dynamodb_table_arn }}"
      enabled: True
      batch_size: 100
      starting_position: LATEST
