# Create dynamo table with hash and range primary key
---
- name: Retrieve DynamoDB Table ARN
  command: python /Users/annadowling/Desktop/CloudArch/ansible-architecture/playbooks/retrieveDynamoDBTableARN.py {{ access_key_id }} {{ secret_access_key }}
  register: table_stream_arn

- name: Print output of retrieved table ARN
  debug:
    msg: "DYNAMODB Table Stream Arn: {{ table_stream_arn.stdout }}"

- name: Create DynamoDB Event Trigger for Aggregation Lambda
  lambda_event:
    region: "{{ region }}"
    aws_access_key: "{{ access_key_id }}"
    aws_secret_key: "{{ secret_access_key }}"
    state: present
    event_source: stream
    lambda_function_arn: "{{ agg_lambda_function }}"
    alias: Dev
    source_params:
      source_arn: "{{ table_stream_arn.stdout }}"
      enabled: True
      batch_size: 100
      starting_position: LATEST
