# Create an SQS Queue for Lambda Update event triggers for use with this Serverless Architecture
# ansible-playbook createSQSQueue.yml --ask-vault-pass

- name: Create an SQS queue to trigger a Lambda event
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - ../group_vars/aws/vault.yml
    - ../group_vars/aws/vars.yml
  roles:
    - role: create_sqs_queue