# Create the DynamoDB Table for use with this Serverless Architecture
# ansible-playbook createDynamodbTable.yml --ask-vault-pass

- name: Create the DynamoDB Table
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - ../group_vars/aws/vault.yml
    - ../group_vars/aws/vars.yml
  roles:
    - role: create_dynamodb_table