# Deletes the previously created SQS Queue
# ansible-playbook deleteSQSQueue.yml --ask-vault-pass

- name: Delete SQS Queue
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - ../group_vars/aws/vault.yml
    - ../group_vars/aws/vars.yml
  roles:
    - role: delete_sqs_queue